name: build-release    #The name of your Github Action on Github.com

on:
  release:
    types:
      - published


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Upload artifacts to Modrinth, Curseforge and GitHub
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: 9HRgyldZ
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: false

          curseforge-id: 816979
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.PB_GITHUB_TOKEN }}
          files: build/libs/!(*-@(dev|sources|all)).jar
          java: 17
          version-type: release
          loaders: fabric quilt

          dependencies: fabric-api | depends | *

          version-resolver: releases # Defaults to selecting the latest compatible version of Minecraft, using the tag from the fabric.mod.json